#!/bin/sh

mkdir /srv/webanno
echo installing Docker
apt update
apt install docker -y
apt install docker.io -y
echo Port to use:
read Port
docker run -it --name webanno -v /srv/webanno:/export -p$Port:$Port webanno/webanno:3.5.7
echo creating systemd service
cp webanno.service /etc/systemd/system/webanno.service
systemctl enable webanno
echo Done!
